import { NextRequest, NextResponse } from "next/server";
import { apiError, requireUser } from "@/lib/api/auth";

export async function GET(
  _request: NextRequest,
  { params }: { params: { run_id: string } }
) {
  const auth = await requireUser();
  if (auth.response) return auth.response;
  const { user, supabase } = auth;

  const { data: output } = await supabase
    .from("skill_outputs")
    .select("storage_path, filename")
    .eq("skill_run_id", params.run_id)
    .eq("user_id", user.id)
    .maybeSingle();

  if (output) {
    const { data: signed } = await supabase.storage
      .from("dsg-outputs")
      .createSignedUrl(output.storage_path, 60 * 60 * 24);
    if (signed?.signedUrl) {
      return NextResponse.redirect(signed.signedUrl);
    }
  }

  // Placeholder fallback for v1 stub when no real .docx exists yet.
  const filename =
    output?.filename ?? `Prospect_Dossier_${params.run_id}.txt`;
  const body = `Prospect Dossier (placeholder)\n\nThe real .docx will be generated by the Python sidecar in v1.1.\n\nRun ID: ${params.run_id}\nGenerated: ${new Date().toISOString()}\n`;
  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename.replace(/\.docx$/, ".txt")}"`,
    },
  });
}

export const dynamic = "force-dynamic";
