import { deflateRawSync } from "zlib";
import type {
  DossierHighlights,
  DossierInput,
} from "@/lib/dossier-schema";

// A minimal Office Open XML (.docx) builder used as a v1 placeholder so the
// in-browser mammoth.js preview renders something real. The Python sidecar
// will replace this with the templated document in v1.1.
export function buildPlaceholderDocx(
  input: DossierInput,
  highlights: DossierHighlights
): Buffer {
  const documentXml = buildDocumentXml(input, highlights);
  const contentTypesXml =
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
    `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
    `<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
    `<Default Extension="xml" ContentType="application/xml"/>` +
    `<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>` +
    `</Types>`;
  const relsXml =
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
    `<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
    `<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>` +
    `</Relationships>`;

  return buildZip([
    { name: "[Content_Types].xml", data: Buffer.from(contentTypesXml, "utf-8") },
    { name: "_rels/.rels", data: Buffer.from(relsXml, "utf-8") },
    { name: "word/document.xml", data: Buffer.from(documentXml, "utf-8") },
  ]);
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function paragraph(
  text: string,
  opts?: { bold?: boolean; color?: string; size?: number }
): string {
  const runProps: string[] = [];
  if (opts?.bold) runProps.push(`<w:b/>`);
  if (opts?.color) runProps.push(`<w:color w:val="${opts.color}"/>`);
  if (opts?.size) runProps.push(`<w:sz w:val="${opts.size * 2}"/>`);
  const rPr = runProps.length ? `<w:rPr>${runProps.join("")}</w:rPr>` : "";
  return `<w:p><w:r>${rPr}<w:t xml:space="preserve">${escapeXml(text)}</w:t></w:r></w:p>`;
}

function spacer(): string {
  return `<w:p/>`;
}

function buildDocumentXml(
  input: DossierInput,
  highlights: DossierHighlights
): string {
  const generated = new Date().toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  const sections: string[] = [
    paragraph("Prospect Dossier", { color: "2E69B3", size: 9, bold: true }),
    paragraph(highlights.company, { size: 18, bold: true }),
    paragraph(`Generated ${generated}`, { color: "6B7280", size: 9 }),
    spacer(),
    paragraph("Opening line", { color: "2E69B3", bold: true, size: 11 }),
    paragraph(highlights.opening_line_preview),
    spacer(),
    paragraph("Strongest signal", { color: "2E69B3", bold: true, size: 11 }),
    paragraph(highlights.strongest_signal),
    spacer(),
    paragraph("Top pain", { color: "2E69B3", bold: true, size: 11 }),
    paragraph(highlights.top_pain),
    spacer(),
    paragraph("Prior touchpoints", { color: "2E69B3", bold: true, size: 11 }),
    paragraph(
      highlights.prior_touchpoints_status === "yes" ? "Yes" : "No"
    ),
  ];

  if (input.meeting_context) {
    sections.push(
      spacer(),
      paragraph("Meeting context", { color: "2E69B3", bold: true, size: 11 }),
      paragraph(input.meeting_context)
    );
  }
  if (input.product_line) {
    sections.push(
      spacer(),
      paragraph("Product line", { color: "2E69B3", bold: true, size: 11 }),
      paragraph(input.product_line)
    );
  }
  if (input.prior_interaction) {
    sections.push(
      spacer(),
      paragraph("Prior interaction", { color: "2E69B3", bold: true, size: 11 }),
      paragraph(input.prior_interaction)
    );
  }

  sections.push(
    spacer(),
    paragraph(
      "Placeholder generated by the v1 stub. The Python sidecar replaces this with the templated dossier in v1.1.",
      { color: "6B7280", size: 9 }
    )
  );

  return (
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
    `<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">` +
    `<w:body>${sections.join("")}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/></w:sectPr></w:body>` +
    `</w:document>`
  );
}

// Minimal ZIP writer (deflate + store) sufficient for the .docx package.
interface ZipEntry {
  name: string;
  data: Buffer;
}

function buildZip(entries: ZipEntry[]): Buffer {
  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let offset = 0;

  for (const entry of entries) {
    const nameBuf = Buffer.from(entry.name, "utf-8");
    const crc = crc32(entry.data);
    const compressed = deflateRawSync(entry.data);
    const useDeflate = compressed.length < entry.data.length;
    const stored = useDeflate ? compressed : entry.data;
    const method = useDeflate ? 8 : 0;

    const localHeader = Buffer.alloc(30);
    localHeader.writeUInt32LE(0x04034b50, 0);
    localHeader.writeUInt16LE(20, 4);
    localHeader.writeUInt16LE(0, 6);
    localHeader.writeUInt16LE(method, 8);
    localHeader.writeUInt16LE(0, 10);
    localHeader.writeUInt16LE(0, 12);
    localHeader.writeUInt32LE(crc, 14);
    localHeader.writeUInt32LE(stored.length, 18);
    localHeader.writeUInt32LE(entry.data.length, 22);
    localHeader.writeUInt16LE(nameBuf.length, 26);
    localHeader.writeUInt16LE(0, 28);

    localParts.push(localHeader, nameBuf, stored);

    const centralHeader = Buffer.alloc(46);
    centralHeader.writeUInt32LE(0x02014b50, 0);
    centralHeader.writeUInt16LE(20, 4);
    centralHeader.writeUInt16LE(20, 6);
    centralHeader.writeUInt16LE(0, 8);
    centralHeader.writeUInt16LE(method, 10);
    centralHeader.writeUInt16LE(0, 12);
    centralHeader.writeUInt16LE(0, 14);
    centralHeader.writeUInt32LE(crc, 16);
    centralHeader.writeUInt32LE(stored.length, 20);
    centralHeader.writeUInt32LE(entry.data.length, 24);
    centralHeader.writeUInt16LE(nameBuf.length, 28);
    centralHeader.writeUInt16LE(0, 30);
    centralHeader.writeUInt16LE(0, 32);
    centralHeader.writeUInt16LE(0, 34);
    centralHeader.writeUInt16LE(0, 36);
    centralHeader.writeUInt32LE(0, 38);
    centralHeader.writeUInt32LE(offset, 42);
    centralParts.push(centralHeader, nameBuf);

    offset += localHeader.length + nameBuf.length + stored.length;
  }

  const centralBuffer = Buffer.concat(centralParts);
  const localBuffer = Buffer.concat(localParts);

  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(0, 4);
  end.writeUInt16LE(0, 6);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(centralBuffer.length, 12);
  end.writeUInt32LE(localBuffer.length, 16);
  end.writeUInt16LE(0, 20);

  return Buffer.concat([localBuffer, centralBuffer, end]);
}

let crcTable: Uint32Array | null = null;

function crc32(buf: Buffer): number {
  if (!crcTable) {
    crcTable = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
      let c = n;
      for (let k = 0; k < 8; k++) {
        c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
      }
      crcTable[n] = c >>> 0;
    }
  }
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) {
    c = (crcTable[(c ^ buf[i]) & 0xff] ^ (c >>> 8)) >>> 0;
  }
  return (c ^ 0xffffffff) >>> 0;
}
